### Create Poll

POST http://localhost:3000/api/admin/poll HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "endDate": "{{$date}}",
  "options": [
    {
      "name": "Option 1",
      "vote": "IN"
    },
    {
      "name": "Option 2",
      "vote": "OUT"
    },
    {
      "name": "Option 3",
      "vote": "SOLO"
    }
  ],
  "question": "Question 2",
  "tournamentId": "c8ac13c9-3529-44f4-a221-9476484c6c46"
}


### 

GET http://localhost:3000/api/polls HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{TOKEN}}
