### 

# @name scratchpad

POST http://localhost:3000/api/auth/signup HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "email": "harrison@gmail.com",
  "password": "123Clashofclan@",
  "userName": "harrison"
}


### 

# @name get user

GET http://localhost:3000/api/auth HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{TOKEN}}
