### 

# @name scratchpad

POST http://localhost:3000/api/auth/signup HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "email": "jyrwaboy@gmail.com",
  "password": "123Clashofclan@",
  "userName": "jyrwaboy"
}
