### 

@id = 0fb816eb-e85a-47c5-a788-79e07a1f9d68


### 

# @name GEt team by tournamentId

GET http://localhost:3000/api/tournament/{{id}}/team HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{TOKEN}}


### 

# @name Create tournament Team

POST http://localhost:3000/api/admin/tournament/{{id}}/team?team=4 HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "name": "Team 1"
}


### 

# @name delete teams by tournament id

DELETE http://localhost:3000/api/admin/tournament/{{id}}/team HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{TOKEN}}
