### 

GET http://localhost:3000/api/season HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{TOKEN}}


### 

POST http://localhost:3000/api/admin/season HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "name": "Test",
  "startDate": "{{$date}}"
}
