import { z } from "zod";

import { createEnv } from "@t3-oss/env";

export const env = createEnv({
  server: {
    DATABASE_URL: z.url(),
    OPEN_AI_API_KEY: z.string().min(1),
    CLERK_SECRET_KEY: z.string().min(1),
    SUPABASE_URL: z.url(),
    SUPABASE_API_KEY: z.string().min(1),
    SUPABASE_PUBLISHABLE_KEY: z.string().min(1),
    SUPABASE_BUCKET_NAME: z.string().min(1),
    DIRECT_URL: z.url().optional(),
    FIREBASE_PROJECT_ID: z.string().min(1),
    FIREBASE_CLIENT_EMAIL: z.email(),
    FIREBASE_PRIVATE_KEY: z.string().min(1),
    ADMIN_JOB_SECRET: z.string().min(1),
    // add more secrets as needed
  },
  client: {
    NEXT_PUBLIC_API_URL: z.url(),
    NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: z.string().min(1),
    NEXT_PUBLIC_FIREBASE_API_KEY: z.string().min(1),
    NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: z.string().min(1),
    NEXT_PUBLIC_FIREBASE_PROJECT_ID: z.string().min(1),
    NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: z.string().min(1),
    NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: z.string().min(1),
    NEXT_PUBLIC_FIREBASE_APP_ID: z.string().min(1),
    NEXT_PUBLIC_ADMIN_JOB_SECRET: z.string().min(1),
    NEXT_PUBLIC_ADSENSE_PUBLISHER_ID: z.string().min(1),
    NEXT_PUBLIC_ADSENSE_BANNER_ID: z.string().min(1),
    NEXT_PUBLIC_ADSENSE_INTERSTITIAL_ID: z.string().min(1),
    NEXT_PUBLIC_ADSENSE_REWARDED_ID: z.string().min(1),
    NEXT_PUBLIC_APP_VERSION: z.string().min(1),
    NEXT_PUBLIC_BUILD_TIME: z.string().min(1),
    NEXT_PUBLIC_COMMIT_HASH: z.string().min(1),
    // add more public vars as needed
  },

  runtimeEnv: {
    DATABASE_URL: process.env.DATABASE_URL,
    OPEN_AI_API_KEY: process.env.OPEN_AI_API_KEY,
    CLERK_SECRET_KEY: process.env.CLERK_SECRET_KEY,
    SUPABASE_URL: process.env.SUPABASE_URL,
    SUPABASE_API_KEY: process.env.SUPABASE_API_KEY,
    SUPABASE_PUBLISHABLE_KEY: process.env.SUPABASE_PUBLISHABLE_KEY,
    SUPABASE_BUCKET_NAME: process.env.SUPABASE_BUCKET_NAME,
    DIRECT_URL: process.env.DIRECT_URL,
    FIREBASE_PROJECT_ID: process.env.FIREBASE_PROJECT_ID,
    FIREBASE_CLIENT_EMAIL: process.env.FIREBASE_CLIENT_EMAIL,
    FIREBASE_PRIVATE_KEY: process.env.FIREBASE_PRIVATE_KEY,
    ADMIN_JOB_SECRET: process.env.ADMIN_JOB_SECRET,
    NEXT_PUBLIC_API_URL: process.env.NEXT_PUBLIC_API_URL,
    NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY:
      process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY,
    NEXT_PUBLIC_FIREBASE_API_KEY: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
    NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN:
      process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
    NEXT_PUBLIC_FIREBASE_PROJECT_ID:
      process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
    NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET:
      process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
    NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID:
      process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
    NEXT_PUBLIC_FIREBASE_APP_ID: process.env.NEXT_PUBLIC_FIREBASE_APP_ID,
    NEXT_PUBLIC_ADMIN_JOB_SECRET: process.env.NEXT_PUBLIC_ADMIN_JOB_SECRET,
    NEXT_PUBLIC_ADSENSE_PUBLISHER_ID:
      process.env.NEXT_PUBLIC_ADSENSE_PUBLISHER_ID,
    NEXT_PUBLIC_ADSENSE_BANNER_ID: process.env.NEXT_PUBLIC_ADSENSE_BANNER_ID,
    NEXT_PUBLIC_ADSENSE_INTERSTITIAL_ID:
      process.env.NEXT_PUBLIC_ADSENSE_INTERSTITIAL_ID,
    NEXT_PUBLIC_ADSENSE_REWARDED_ID:
      process.env.NEXT_PUBLIC_ADSENSE_REWARDED_ID,
    NEXT_PUBLIC_APP_VERSION: process.env.NEXT_PUBLIC_APP_VERSION,
    NEXT_PUBLIC_BUILD_TIME: process.env.NEXT_PUBLIC_BUILD_TIME,
    NEXT_PUBLIC_COMMIT_HASH: process.env.NEXT_PUBLIC_COMMIT_HASH,
  },
});
